<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <!--<ProjectReference Include="..\..\..\WoowzLib.Core\WoowzLib.Core.csproj" />
      <ProjectReference Include="..\..\..\WoowzLib.Logger\WoowzLib.Logger.csproj" />-->
        <ProjectReference Include="..\..\..\WoowzLib.Window\WoowzLib.Window.csproj" />
      <ProjectReference Include="..\..\..\WoowzLib.Parser\WoowzLib.Parser.csproj" />
      <ProjectReference Include="..\..\..\WoowzLib.Render\WoowzLib.Render.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Woowz11.WoowzLib.Logger" Version="0.0.1" />
    </ItemGroup>
    
</Project>
