<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        
        <Version>0.0.1.505</Version>
    </PropertyGroup>

    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
      <Exec Command="&quot;W:\Other\WoowzLib\VersionUpdater\bin\Release\net8.0\VersionUpdater.exe&quot; &quot;W:\Other\WoowzLib\WoowzLib.Base\WoowzLib.Base.csproj&quot;" />
    </Target>

</Project>