<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Release</Configurations>
        <Platforms>AnyCPU</Platforms>

        <Version>0.0.1.78</Version>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WoowzLib.Algorithm\WoowzLib.Algorithm.csproj" />
      <ProjectReference Include="..\WoowzLib.System\WoowzLib.System.csproj" />
    </ItemGroup>

    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
        <Exec Command="&quot;W:\Other\WoowzLib\VersionUpdater\bin\Release\net8.0\VersionUpdater.exe&quot; &quot;W:\Other\WoowzLib\WoowzLib.Window\WoowzLib.Window.csproj&quot;" />
    </Target>
</Project>
