<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Release</Configurations>
        <Platforms>AnyCPU</Platforms>

        <Version>0.0.0.61</Version>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WoowzLib.Base\WoowzLib.Base.csproj" />
      <ProjectReference Include="..\WoowzLib.Core\WoowzLib.Core.csproj" />
      <ProjectReference Include="..\WoowzLib.Math\WoowzLib.Math.csproj" />
    </ItemGroup>

    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
        <Exec Command="&quot;W:\Other\WoowzLib\VersionUpdater\bin\Release\net8.0\VersionUpdater.exe&quot; &quot;W:\Other\WoowzLib\WoowzLib.Algorithm\WoowzLib.Algorithm.csproj&quot;" />
    </Target>

</Project>
