<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <IncludeDocumentationFile>true</IncludeDocumentationFile>
        
        <PackageId>Woowz11.WoowzLib</PackageId>
        <Version>0.0.4.44</Version>
        <Authors>Woowz11</Authors>
        <Description>The core for WoowzLib</Description>
        <PackageLicenseExpression>CC-BY-SA-4.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/Woowz11/WoowzLib/tree/main/WoowzLib.Core</RepositoryUrl>
        <IsPackable>true</IsPackable>
        <PackageTags>Woowz;Library;Math;Windows;System;Byte;Vector;Color;Rect;String;Native;HDC;Input;Random;Time;Easy;Game;Console;Explorer;File;Folder;Image;Russian</PackageTags>
        <PackageIcon>Icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="Icon.png"  Pack="true" PackagePath="/" />
        <None Include="README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

</Project>