/* Сгенерировано с помощью WoowzLibGenerator 0.0.0.336, внутри класса "Tests.cs" */
using WLO.Vector;
namespace WoowzLibTest.Tests;
public static class Test_Vector{
	public static void Run(){
		Test.Run("Vector2I (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector2I();
				Test.CheckResult<int>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<int>(v.Y, 0, "Создание Y не работает!");
				v = new Vector2I(0, 1);
				Test.CheckResult<int>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<int>(v.Y, 1, "Создание 2 Y не работает!");
				v = new Vector2I(555);
				Test.CheckResult<int>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<int>(v.Y, 555, "Создание 3 Y не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector2I();
				v.X = 32;
				v.Y = 32;
				Test.CheckResult<int>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Y не работает!");
				v = v.Add(Vector2I.One);
				Test.CheckResult<int>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<int>(v.Y, 33, "Изменение Add Y не работает!");
				v = v.Sub(Vector2I.One);
				Test.CheckResult<int>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Sub Y не работает!");
				v = v.Mul(Vector2I.Double);
				Test.CheckResult<int>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<int>(v.Y, 64, "Изменение Mul Y не работает!");
				v = v.Div(Vector2I.Double);
				Test.CheckResult<int>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Div Y не работает!");
				v = v + Vector2I.One;
				Test.CheckResult<int>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<int>(v.Y, 33, "Изменение Add 2 Y не работает!");
				v = v - Vector2I.One;
				Test.CheckResult<int>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				v = v * Vector2I.Double;
				Test.CheckResult<int>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<int>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				v = v / Vector2I.Double;
				Test.CheckResult<int>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Div 2 Y не работает!");
				v = v + 1;
				Test.CheckResult<int>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<int>(v.Y, 33, "Изменение Add 3 Y не работает!");
				v = v - 1;
				Test.CheckResult<int>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				v = v * 2;
				Test.CheckResult<int>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<int>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				v = v / 2;
				Test.CheckResult<int>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Div 3 Y не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector2I.Right.Mul(Vector2I.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector2I.Right.Mul(Vector2I.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector2I.One, false, "Сравнение 6 не работает!");
			});
		});
		Test.Run("Vector3I (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector3I();
				Test.CheckResult<int>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<int>(v.Y, 0, "Создание Y не работает!");
				Test.CheckResult<int>(v.Z, 0, "Создание Z не работает!");
				v = new Vector3I(0, 1, 2);
				Test.CheckResult<int>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<int>(v.Y, 1, "Создание 2 Y не работает!");
				Test.CheckResult<int>(v.Z, 2, "Создание 2 Z не работает!");
				v = new Vector3I(555);
				Test.CheckResult<int>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<int>(v.Y, 555, "Создание 3 Y не работает!");
				Test.CheckResult<int>(v.Z, 555, "Создание 3 Z не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector3I();
				v.X = 32;
				v.Y = 32;
				v.Z = 32;
				Test.CheckResult<int>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Z не работает!");
				v = v.Add(Vector3I.One);
				Test.CheckResult<int>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<int>(v.Y, 33, "Изменение Add Y не работает!");
				Test.CheckResult<int>(v.Z, 33, "Изменение Add Z не работает!");
				v = v.Sub(Vector3I.One);
				Test.CheckResult<int>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Sub Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Sub Z не работает!");
				v = v.Mul(Vector3I.Double);
				Test.CheckResult<int>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<int>(v.Y, 64, "Изменение Mul Y не работает!");
				Test.CheckResult<int>(v.Z, 64, "Изменение Mul Z не работает!");
				v = v.Div(Vector3I.Double);
				Test.CheckResult<int>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Div Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Div Z не работает!");
				v = v + Vector3I.One;
				Test.CheckResult<int>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<int>(v.Y, 33, "Изменение Add 2 Y не работает!");
				Test.CheckResult<int>(v.Z, 33, "Изменение Add 2 Z не работает!");
				v = v - Vector3I.One;
				Test.CheckResult<int>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Sub 2 Z не работает!");
				v = v * Vector3I.Double;
				Test.CheckResult<int>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<int>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				Test.CheckResult<int>(v.Z, 64, "Изменение Mul 2 Z не работает!");
				v = v / Vector3I.Double;
				Test.CheckResult<int>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Div 2 Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Div 2 Z не работает!");
				v = v + 1;
				Test.CheckResult<int>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<int>(v.Y, 33, "Изменение Add 3 Y не работает!");
				Test.CheckResult<int>(v.Z, 33, "Изменение Add 3 Z не работает!");
				v = v - 1;
				Test.CheckResult<int>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Sub 3 Z не работает!");
				v = v * 2;
				Test.CheckResult<int>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<int>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				Test.CheckResult<int>(v.Z, 64, "Изменение Mul 3 Z не работает!");
				v = v / 2;
				Test.CheckResult<int>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Div 3 Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Div 3 Z не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector3I.Right.Mul(Vector3I.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector3I.Right.Mul(Vector3I.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector3I.One, false, "Сравнение 6 не работает!");
			});
		});
		Test.Run("Vector4I (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector4I();
				Test.CheckResult<int>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<int>(v.Y, 0, "Создание Y не работает!");
				Test.CheckResult<int>(v.Z, 0, "Создание Z не работает!");
				Test.CheckResult<int>(v.W, 0, "Создание W не работает!");
				v = new Vector4I(0, 1, 2, 3);
				Test.CheckResult<int>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<int>(v.Y, 1, "Создание 2 Y не работает!");
				Test.CheckResult<int>(v.Z, 2, "Создание 2 Z не работает!");
				Test.CheckResult<int>(v.W, 3, "Создание 2 W не работает!");
				v = new Vector4I(555);
				Test.CheckResult<int>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<int>(v.Y, 555, "Создание 3 Y не работает!");
				Test.CheckResult<int>(v.Z, 555, "Создание 3 Z не работает!");
				Test.CheckResult<int>(v.W, 555, "Создание 3 W не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector4I();
				v.X = 32;
				v.Y = 32;
				v.Z = 32;
				v.W = 32;
				Test.CheckResult<int>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Z не работает!");
				Test.CheckResult<int>(v.W, 32, "Изменение W не работает!");
				v = v.Add(Vector4I.One);
				Test.CheckResult<int>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<int>(v.Y, 33, "Изменение Add Y не работает!");
				Test.CheckResult<int>(v.Z, 33, "Изменение Add Z не работает!");
				Test.CheckResult<int>(v.W, 33, "Изменение Add W не работает!");
				v = v.Sub(Vector4I.One);
				Test.CheckResult<int>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Sub Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Sub Z не работает!");
				Test.CheckResult<int>(v.W, 32, "Изменение Sub W не работает!");
				v = v.Mul(Vector4I.Double);
				Test.CheckResult<int>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<int>(v.Y, 64, "Изменение Mul Y не работает!");
				Test.CheckResult<int>(v.Z, 64, "Изменение Mul Z не работает!");
				Test.CheckResult<int>(v.W, 64, "Изменение Mul W не работает!");
				v = v.Div(Vector4I.Double);
				Test.CheckResult<int>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Div Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Div Z не работает!");
				Test.CheckResult<int>(v.W, 32, "Изменение Div W не работает!");
				v = v + Vector4I.One;
				Test.CheckResult<int>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<int>(v.Y, 33, "Изменение Add 2 Y не работает!");
				Test.CheckResult<int>(v.Z, 33, "Изменение Add 2 Z не работает!");
				Test.CheckResult<int>(v.W, 33, "Изменение Add 2 W не работает!");
				v = v - Vector4I.One;
				Test.CheckResult<int>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Sub 2 Z не работает!");
				Test.CheckResult<int>(v.W, 32, "Изменение Sub 2 W не работает!");
				v = v * Vector4I.Double;
				Test.CheckResult<int>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<int>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				Test.CheckResult<int>(v.Z, 64, "Изменение Mul 2 Z не работает!");
				Test.CheckResult<int>(v.W, 64, "Изменение Mul 2 W не работает!");
				v = v / Vector4I.Double;
				Test.CheckResult<int>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Div 2 Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Div 2 Z не работает!");
				Test.CheckResult<int>(v.W, 32, "Изменение Div 2 W не работает!");
				v = v + 1;
				Test.CheckResult<int>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<int>(v.Y, 33, "Изменение Add 3 Y не работает!");
				Test.CheckResult<int>(v.Z, 33, "Изменение Add 3 Z не работает!");
				Test.CheckResult<int>(v.W, 33, "Изменение Add 3 W не работает!");
				v = v - 1;
				Test.CheckResult<int>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Sub 3 Z не работает!");
				Test.CheckResult<int>(v.W, 32, "Изменение Sub 3 W не работает!");
				v = v * 2;
				Test.CheckResult<int>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<int>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				Test.CheckResult<int>(v.Z, 64, "Изменение Mul 3 Z не работает!");
				Test.CheckResult<int>(v.W, 64, "Изменение Mul 3 W не работает!");
				v = v / 2;
				Test.CheckResult<int>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<int>(v.Y, 32, "Изменение Div 3 Y не работает!");
				Test.CheckResult<int>(v.Z, 32, "Изменение Div 3 Z не работает!");
				Test.CheckResult<int>(v.W, 32, "Изменение Div 3 W не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector4I.Right.Mul(Vector4I.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector4I.Right.Mul(Vector4I.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector4I.One, false, "Сравнение 6 не работает!");
			});
		});
		Test.Run("Vector2UI (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector2UI();
				Test.CheckResult<uint>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<uint>(v.Y, 0, "Создание Y не работает!");
				v = new Vector2UI(0, 1);
				Test.CheckResult<uint>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 1, "Создание 2 Y не работает!");
				v = new Vector2UI(555);
				Test.CheckResult<uint>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 555, "Создание 3 Y не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector2UI();
				v.X = 32;
				v.Y = 32;
				Test.CheckResult<uint>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Y не работает!");
				v = v.Add(Vector2UI.One);
				Test.CheckResult<uint>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<uint>(v.Y, 33, "Изменение Add Y не работает!");
				v = v.Sub(Vector2UI.One);
				Test.CheckResult<uint>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Sub Y не работает!");
				v = v.Mul(Vector2UI.Double);
				Test.CheckResult<uint>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<uint>(v.Y, 64, "Изменение Mul Y не работает!");
				v = v.Div(Vector2UI.Double);
				Test.CheckResult<uint>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Div Y не работает!");
				v = v + Vector2UI.One;
				Test.CheckResult<uint>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 33, "Изменение Add 2 Y не работает!");
				v = v - Vector2UI.One;
				Test.CheckResult<uint>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				v = v * Vector2UI.Double;
				Test.CheckResult<uint>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				v = v / Vector2UI.Double;
				Test.CheckResult<uint>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Div 2 Y не работает!");
				v = v + 1;
				Test.CheckResult<uint>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 33, "Изменение Add 3 Y не работает!");
				v = v - 1;
				Test.CheckResult<uint>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				v = v * 2;
				Test.CheckResult<uint>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				v = v / 2;
				Test.CheckResult<uint>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Div 3 Y не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector2UI.Right.Mul(Vector2UI.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector2UI.Right.Mul(Vector2UI.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector2UI.One, false, "Сравнение 6 не работает!");
			});
		});
		Test.Run("Vector3UI (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector3UI();
				Test.CheckResult<uint>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<uint>(v.Y, 0, "Создание Y не работает!");
				Test.CheckResult<uint>(v.Z, 0, "Создание Z не работает!");
				v = new Vector3UI(0, 1, 2);
				Test.CheckResult<uint>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 1, "Создание 2 Y не работает!");
				Test.CheckResult<uint>(v.Z, 2, "Создание 2 Z не работает!");
				v = new Vector3UI(555);
				Test.CheckResult<uint>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 555, "Создание 3 Y не работает!");
				Test.CheckResult<uint>(v.Z, 555, "Создание 3 Z не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector3UI();
				v.X = 32;
				v.Y = 32;
				v.Z = 32;
				Test.CheckResult<uint>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Z не работает!");
				v = v.Add(Vector3UI.One);
				Test.CheckResult<uint>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<uint>(v.Y, 33, "Изменение Add Y не работает!");
				Test.CheckResult<uint>(v.Z, 33, "Изменение Add Z не работает!");
				v = v.Sub(Vector3UI.One);
				Test.CheckResult<uint>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Sub Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Sub Z не работает!");
				v = v.Mul(Vector3UI.Double);
				Test.CheckResult<uint>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<uint>(v.Y, 64, "Изменение Mul Y не работает!");
				Test.CheckResult<uint>(v.Z, 64, "Изменение Mul Z не работает!");
				v = v.Div(Vector3UI.Double);
				Test.CheckResult<uint>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Div Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Div Z не работает!");
				v = v + Vector3UI.One;
				Test.CheckResult<uint>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 33, "Изменение Add 2 Y не работает!");
				Test.CheckResult<uint>(v.Z, 33, "Изменение Add 2 Z не работает!");
				v = v - Vector3UI.One;
				Test.CheckResult<uint>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Sub 2 Z не работает!");
				v = v * Vector3UI.Double;
				Test.CheckResult<uint>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				Test.CheckResult<uint>(v.Z, 64, "Изменение Mul 2 Z не работает!");
				v = v / Vector3UI.Double;
				Test.CheckResult<uint>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Div 2 Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Div 2 Z не работает!");
				v = v + 1;
				Test.CheckResult<uint>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 33, "Изменение Add 3 Y не работает!");
				Test.CheckResult<uint>(v.Z, 33, "Изменение Add 3 Z не работает!");
				v = v - 1;
				Test.CheckResult<uint>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Sub 3 Z не работает!");
				v = v * 2;
				Test.CheckResult<uint>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				Test.CheckResult<uint>(v.Z, 64, "Изменение Mul 3 Z не работает!");
				v = v / 2;
				Test.CheckResult<uint>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Div 3 Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Div 3 Z не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector3UI.Right.Mul(Vector3UI.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector3UI.Right.Mul(Vector3UI.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector3UI.One, false, "Сравнение 6 не работает!");
			});
		});
		Test.Run("Vector4UI (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector4UI();
				Test.CheckResult<uint>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<uint>(v.Y, 0, "Создание Y не работает!");
				Test.CheckResult<uint>(v.Z, 0, "Создание Z не работает!");
				Test.CheckResult<uint>(v.W, 0, "Создание W не работает!");
				v = new Vector4UI(0, 1, 2, 3);
				Test.CheckResult<uint>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 1, "Создание 2 Y не работает!");
				Test.CheckResult<uint>(v.Z, 2, "Создание 2 Z не работает!");
				Test.CheckResult<uint>(v.W, 3, "Создание 2 W не работает!");
				v = new Vector4UI(555);
				Test.CheckResult<uint>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 555, "Создание 3 Y не работает!");
				Test.CheckResult<uint>(v.Z, 555, "Создание 3 Z не работает!");
				Test.CheckResult<uint>(v.W, 555, "Создание 3 W не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector4UI();
				v.X = 32;
				v.Y = 32;
				v.Z = 32;
				v.W = 32;
				Test.CheckResult<uint>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Z не работает!");
				Test.CheckResult<uint>(v.W, 32, "Изменение W не работает!");
				v = v.Add(Vector4UI.One);
				Test.CheckResult<uint>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<uint>(v.Y, 33, "Изменение Add Y не работает!");
				Test.CheckResult<uint>(v.Z, 33, "Изменение Add Z не работает!");
				Test.CheckResult<uint>(v.W, 33, "Изменение Add W не работает!");
				v = v.Sub(Vector4UI.One);
				Test.CheckResult<uint>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Sub Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Sub Z не работает!");
				Test.CheckResult<uint>(v.W, 32, "Изменение Sub W не работает!");
				v = v.Mul(Vector4UI.Double);
				Test.CheckResult<uint>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<uint>(v.Y, 64, "Изменение Mul Y не работает!");
				Test.CheckResult<uint>(v.Z, 64, "Изменение Mul Z не работает!");
				Test.CheckResult<uint>(v.W, 64, "Изменение Mul W не работает!");
				v = v.Div(Vector4UI.Double);
				Test.CheckResult<uint>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Div Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Div Z не работает!");
				Test.CheckResult<uint>(v.W, 32, "Изменение Div W не работает!");
				v = v + Vector4UI.One;
				Test.CheckResult<uint>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 33, "Изменение Add 2 Y не работает!");
				Test.CheckResult<uint>(v.Z, 33, "Изменение Add 2 Z не работает!");
				Test.CheckResult<uint>(v.W, 33, "Изменение Add 2 W не работает!");
				v = v - Vector4UI.One;
				Test.CheckResult<uint>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Sub 2 Z не работает!");
				Test.CheckResult<uint>(v.W, 32, "Изменение Sub 2 W не работает!");
				v = v * Vector4UI.Double;
				Test.CheckResult<uint>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				Test.CheckResult<uint>(v.Z, 64, "Изменение Mul 2 Z не работает!");
				Test.CheckResult<uint>(v.W, 64, "Изменение Mul 2 W не работает!");
				v = v / Vector4UI.Double;
				Test.CheckResult<uint>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Div 2 Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Div 2 Z не работает!");
				Test.CheckResult<uint>(v.W, 32, "Изменение Div 2 W не работает!");
				v = v + 1;
				Test.CheckResult<uint>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 33, "Изменение Add 3 Y не работает!");
				Test.CheckResult<uint>(v.Z, 33, "Изменение Add 3 Z не работает!");
				Test.CheckResult<uint>(v.W, 33, "Изменение Add 3 W не работает!");
				v = v - 1;
				Test.CheckResult<uint>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Sub 3 Z не работает!");
				Test.CheckResult<uint>(v.W, 32, "Изменение Sub 3 W не работает!");
				v = v * 2;
				Test.CheckResult<uint>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				Test.CheckResult<uint>(v.Z, 64, "Изменение Mul 3 Z не работает!");
				Test.CheckResult<uint>(v.W, 64, "Изменение Mul 3 W не работает!");
				v = v / 2;
				Test.CheckResult<uint>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<uint>(v.Y, 32, "Изменение Div 3 Y не работает!");
				Test.CheckResult<uint>(v.Z, 32, "Изменение Div 3 Z не работает!");
				Test.CheckResult<uint>(v.W, 32, "Изменение Div 3 W не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector4UI.Right.Mul(Vector4UI.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector4UI.Right.Mul(Vector4UI.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector4UI.One, false, "Сравнение 6 не работает!");
			});
		});
		Test.Run("Vector2F (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector2F();
				Test.CheckResult<float>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<float>(v.Y, 0, "Создание Y не работает!");
				v = new Vector2F(0, 1);
				Test.CheckResult<float>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<float>(v.Y, 1, "Создание 2 Y не работает!");
				v = new Vector2F(555);
				Test.CheckResult<float>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<float>(v.Y, 555, "Создание 3 Y не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector2F();
				v.X = 32;
				v.Y = 32;
				Test.CheckResult<float>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Y не работает!");
				v = v.Add(Vector2F.One);
				Test.CheckResult<float>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<float>(v.Y, 33, "Изменение Add Y не работает!");
				v = v.Sub(Vector2F.One);
				Test.CheckResult<float>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Sub Y не работает!");
				v = v.Mul(Vector2F.Double);
				Test.CheckResult<float>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<float>(v.Y, 64, "Изменение Mul Y не работает!");
				v = v.Div(Vector2F.Double);
				Test.CheckResult<float>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Div Y не работает!");
				v = v + Vector2F.One;
				Test.CheckResult<float>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<float>(v.Y, 33, "Изменение Add 2 Y не работает!");
				v = v - Vector2F.One;
				Test.CheckResult<float>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				v = v * Vector2F.Double;
				Test.CheckResult<float>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<float>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				v = v / Vector2F.Double;
				Test.CheckResult<float>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Div 2 Y не работает!");
				v = v + 1;
				Test.CheckResult<float>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<float>(v.Y, 33, "Изменение Add 3 Y не работает!");
				v = v - 1;
				Test.CheckResult<float>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				v = v * 2;
				Test.CheckResult<float>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<float>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				v = v / 2;
				Test.CheckResult<float>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Div 3 Y не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector2F.Right.Mul(Vector2F.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector2F.Right.Mul(Vector2F.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector2F.One, false, "Сравнение 6 не работает!");
			});
		});
		Test.Run("Vector3F (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector3F();
				Test.CheckResult<float>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<float>(v.Y, 0, "Создание Y не работает!");
				Test.CheckResult<float>(v.Z, 0, "Создание Z не работает!");
				v = new Vector3F(0, 1, 2);
				Test.CheckResult<float>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<float>(v.Y, 1, "Создание 2 Y не работает!");
				Test.CheckResult<float>(v.Z, 2, "Создание 2 Z не работает!");
				v = new Vector3F(555);
				Test.CheckResult<float>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<float>(v.Y, 555, "Создание 3 Y не работает!");
				Test.CheckResult<float>(v.Z, 555, "Создание 3 Z не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector3F();
				v.X = 32;
				v.Y = 32;
				v.Z = 32;
				Test.CheckResult<float>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Z не работает!");
				v = v.Add(Vector3F.One);
				Test.CheckResult<float>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<float>(v.Y, 33, "Изменение Add Y не работает!");
				Test.CheckResult<float>(v.Z, 33, "Изменение Add Z не работает!");
				v = v.Sub(Vector3F.One);
				Test.CheckResult<float>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Sub Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Sub Z не работает!");
				v = v.Mul(Vector3F.Double);
				Test.CheckResult<float>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<float>(v.Y, 64, "Изменение Mul Y не работает!");
				Test.CheckResult<float>(v.Z, 64, "Изменение Mul Z не работает!");
				v = v.Div(Vector3F.Double);
				Test.CheckResult<float>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Div Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Div Z не работает!");
				v = v + Vector3F.One;
				Test.CheckResult<float>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<float>(v.Y, 33, "Изменение Add 2 Y не работает!");
				Test.CheckResult<float>(v.Z, 33, "Изменение Add 2 Z не работает!");
				v = v - Vector3F.One;
				Test.CheckResult<float>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Sub 2 Z не работает!");
				v = v * Vector3F.Double;
				Test.CheckResult<float>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<float>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				Test.CheckResult<float>(v.Z, 64, "Изменение Mul 2 Z не работает!");
				v = v / Vector3F.Double;
				Test.CheckResult<float>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Div 2 Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Div 2 Z не работает!");
				v = v + 1;
				Test.CheckResult<float>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<float>(v.Y, 33, "Изменение Add 3 Y не работает!");
				Test.CheckResult<float>(v.Z, 33, "Изменение Add 3 Z не работает!");
				v = v - 1;
				Test.CheckResult<float>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Sub 3 Z не работает!");
				v = v * 2;
				Test.CheckResult<float>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<float>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				Test.CheckResult<float>(v.Z, 64, "Изменение Mul 3 Z не работает!");
				v = v / 2;
				Test.CheckResult<float>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Div 3 Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Div 3 Z не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector3F.Right.Mul(Vector3F.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector3F.Right.Mul(Vector3F.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector3F.One, false, "Сравнение 6 не работает!");
			});
		});
		Test.Run("Vector4F (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector4F();
				Test.CheckResult<float>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<float>(v.Y, 0, "Создание Y не работает!");
				Test.CheckResult<float>(v.Z, 0, "Создание Z не работает!");
				Test.CheckResult<float>(v.W, 0, "Создание W не работает!");
				v = new Vector4F(0, 1, 2, 3);
				Test.CheckResult<float>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<float>(v.Y, 1, "Создание 2 Y не работает!");
				Test.CheckResult<float>(v.Z, 2, "Создание 2 Z не работает!");
				Test.CheckResult<float>(v.W, 3, "Создание 2 W не работает!");
				v = new Vector4F(555);
				Test.CheckResult<float>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<float>(v.Y, 555, "Создание 3 Y не работает!");
				Test.CheckResult<float>(v.Z, 555, "Создание 3 Z не работает!");
				Test.CheckResult<float>(v.W, 555, "Создание 3 W не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector4F();
				v.X = 32;
				v.Y = 32;
				v.Z = 32;
				v.W = 32;
				Test.CheckResult<float>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Z не работает!");
				Test.CheckResult<float>(v.W, 32, "Изменение W не работает!");
				v = v.Add(Vector4F.One);
				Test.CheckResult<float>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<float>(v.Y, 33, "Изменение Add Y не работает!");
				Test.CheckResult<float>(v.Z, 33, "Изменение Add Z не работает!");
				Test.CheckResult<float>(v.W, 33, "Изменение Add W не работает!");
				v = v.Sub(Vector4F.One);
				Test.CheckResult<float>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Sub Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Sub Z не работает!");
				Test.CheckResult<float>(v.W, 32, "Изменение Sub W не работает!");
				v = v.Mul(Vector4F.Double);
				Test.CheckResult<float>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<float>(v.Y, 64, "Изменение Mul Y не работает!");
				Test.CheckResult<float>(v.Z, 64, "Изменение Mul Z не работает!");
				Test.CheckResult<float>(v.W, 64, "Изменение Mul W не работает!");
				v = v.Div(Vector4F.Double);
				Test.CheckResult<float>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Div Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Div Z не работает!");
				Test.CheckResult<float>(v.W, 32, "Изменение Div W не работает!");
				v = v + Vector4F.One;
				Test.CheckResult<float>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<float>(v.Y, 33, "Изменение Add 2 Y не работает!");
				Test.CheckResult<float>(v.Z, 33, "Изменение Add 2 Z не работает!");
				Test.CheckResult<float>(v.W, 33, "Изменение Add 2 W не работает!");
				v = v - Vector4F.One;
				Test.CheckResult<float>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Sub 2 Z не работает!");
				Test.CheckResult<float>(v.W, 32, "Изменение Sub 2 W не работает!");
				v = v * Vector4F.Double;
				Test.CheckResult<float>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<float>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				Test.CheckResult<float>(v.Z, 64, "Изменение Mul 2 Z не работает!");
				Test.CheckResult<float>(v.W, 64, "Изменение Mul 2 W не работает!");
				v = v / Vector4F.Double;
				Test.CheckResult<float>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Div 2 Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Div 2 Z не работает!");
				Test.CheckResult<float>(v.W, 32, "Изменение Div 2 W не работает!");
				v = v + 1;
				Test.CheckResult<float>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<float>(v.Y, 33, "Изменение Add 3 Y не работает!");
				Test.CheckResult<float>(v.Z, 33, "Изменение Add 3 Z не работает!");
				Test.CheckResult<float>(v.W, 33, "Изменение Add 3 W не работает!");
				v = v - 1;
				Test.CheckResult<float>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Sub 3 Z не работает!");
				Test.CheckResult<float>(v.W, 32, "Изменение Sub 3 W не работает!");
				v = v * 2;
				Test.CheckResult<float>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<float>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				Test.CheckResult<float>(v.Z, 64, "Изменение Mul 3 Z не работает!");
				Test.CheckResult<float>(v.W, 64, "Изменение Mul 3 W не работает!");
				v = v / 2;
				Test.CheckResult<float>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<float>(v.Y, 32, "Изменение Div 3 Y не работает!");
				Test.CheckResult<float>(v.Z, 32, "Изменение Div 3 Z не работает!");
				Test.CheckResult<float>(v.W, 32, "Изменение Div 3 W не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector4F.Right.Mul(Vector4F.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector4F.Right.Mul(Vector4F.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector4F.One, false, "Сравнение 6 не работает!");
			});
		});
		Test.Run("Vector2D (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector2D();
				Test.CheckResult<double>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<double>(v.Y, 0, "Создание Y не работает!");
				v = new Vector2D(0, 1);
				Test.CheckResult<double>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<double>(v.Y, 1, "Создание 2 Y не работает!");
				v = new Vector2D(555);
				Test.CheckResult<double>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<double>(v.Y, 555, "Создание 3 Y не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector2D();
				v.X = 32;
				v.Y = 32;
				Test.CheckResult<double>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Y не работает!");
				v = v.Add(Vector2D.One);
				Test.CheckResult<double>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<double>(v.Y, 33, "Изменение Add Y не работает!");
				v = v.Sub(Vector2D.One);
				Test.CheckResult<double>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Sub Y не работает!");
				v = v.Mul(Vector2D.Double);
				Test.CheckResult<double>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<double>(v.Y, 64, "Изменение Mul Y не работает!");
				v = v.Div(Vector2D.Double);
				Test.CheckResult<double>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Div Y не работает!");
				v = v + Vector2D.One;
				Test.CheckResult<double>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<double>(v.Y, 33, "Изменение Add 2 Y не работает!");
				v = v - Vector2D.One;
				Test.CheckResult<double>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				v = v * Vector2D.Double;
				Test.CheckResult<double>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<double>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				v = v / Vector2D.Double;
				Test.CheckResult<double>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Div 2 Y не работает!");
				v = v + 1;
				Test.CheckResult<double>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<double>(v.Y, 33, "Изменение Add 3 Y не работает!");
				v = v - 1;
				Test.CheckResult<double>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				v = v * 2;
				Test.CheckResult<double>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<double>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				v = v / 2;
				Test.CheckResult<double>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Div 3 Y не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector2D.Right.Mul(Vector2D.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector2D.Right.Mul(Vector2D.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector2D.One, false, "Сравнение 6 не работает!");
			});
		});
		Test.Run("Vector3D (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector3D();
				Test.CheckResult<double>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<double>(v.Y, 0, "Создание Y не работает!");
				Test.CheckResult<double>(v.Z, 0, "Создание Z не работает!");
				v = new Vector3D(0, 1, 2);
				Test.CheckResult<double>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<double>(v.Y, 1, "Создание 2 Y не работает!");
				Test.CheckResult<double>(v.Z, 2, "Создание 2 Z не работает!");
				v = new Vector3D(555);
				Test.CheckResult<double>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<double>(v.Y, 555, "Создание 3 Y не работает!");
				Test.CheckResult<double>(v.Z, 555, "Создание 3 Z не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector3D();
				v.X = 32;
				v.Y = 32;
				v.Z = 32;
				Test.CheckResult<double>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Z не работает!");
				v = v.Add(Vector3D.One);
				Test.CheckResult<double>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<double>(v.Y, 33, "Изменение Add Y не работает!");
				Test.CheckResult<double>(v.Z, 33, "Изменение Add Z не работает!");
				v = v.Sub(Vector3D.One);
				Test.CheckResult<double>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Sub Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Sub Z не работает!");
				v = v.Mul(Vector3D.Double);
				Test.CheckResult<double>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<double>(v.Y, 64, "Изменение Mul Y не работает!");
				Test.CheckResult<double>(v.Z, 64, "Изменение Mul Z не работает!");
				v = v.Div(Vector3D.Double);
				Test.CheckResult<double>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Div Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Div Z не работает!");
				v = v + Vector3D.One;
				Test.CheckResult<double>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<double>(v.Y, 33, "Изменение Add 2 Y не работает!");
				Test.CheckResult<double>(v.Z, 33, "Изменение Add 2 Z не работает!");
				v = v - Vector3D.One;
				Test.CheckResult<double>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Sub 2 Z не работает!");
				v = v * Vector3D.Double;
				Test.CheckResult<double>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<double>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				Test.CheckResult<double>(v.Z, 64, "Изменение Mul 2 Z не работает!");
				v = v / Vector3D.Double;
				Test.CheckResult<double>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Div 2 Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Div 2 Z не работает!");
				v = v + 1;
				Test.CheckResult<double>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<double>(v.Y, 33, "Изменение Add 3 Y не работает!");
				Test.CheckResult<double>(v.Z, 33, "Изменение Add 3 Z не работает!");
				v = v - 1;
				Test.CheckResult<double>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Sub 3 Z не работает!");
				v = v * 2;
				Test.CheckResult<double>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<double>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				Test.CheckResult<double>(v.Z, 64, "Изменение Mul 3 Z не работает!");
				v = v / 2;
				Test.CheckResult<double>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Div 3 Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Div 3 Z не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector3D.Right.Mul(Vector3D.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector3D.Right.Mul(Vector3D.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector3D.One, false, "Сравнение 6 не работает!");
			});
		});
		Test.Run("Vector4D (GENERATED)", () => {
			Test.F("Создание", () => {
				var v = new Vector4D();
				Test.CheckResult<double>(v.X, 0, "Создание X не работает!");
				Test.CheckResult<double>(v.Y, 0, "Создание Y не работает!");
				Test.CheckResult<double>(v.Z, 0, "Создание Z не работает!");
				Test.CheckResult<double>(v.W, 0, "Создание W не работает!");
				v = new Vector4D(0, 1, 2, 3);
				Test.CheckResult<double>(v.X, 0, "Создание 2 X не работает!");
				Test.CheckResult<double>(v.Y, 1, "Создание 2 Y не работает!");
				Test.CheckResult<double>(v.Z, 2, "Создание 2 Z не работает!");
				Test.CheckResult<double>(v.W, 3, "Создание 2 W не работает!");
				v = new Vector4D(555);
				Test.CheckResult<double>(v.X, 555, "Создание 3 X не работает!");
				Test.CheckResult<double>(v.Y, 555, "Создание 3 Y не работает!");
				Test.CheckResult<double>(v.Z, 555, "Создание 3 Z не работает!");
				Test.CheckResult<double>(v.W, 555, "Создание 3 W не работает!");
			});
			Test.F("Изменение", () => {
				var v = new Vector4D();
				v.X = 32;
				v.Y = 32;
				v.Z = 32;
				v.W = 32;
				Test.CheckResult<double>(v.X, 32, "Изменение X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Z не работает!");
				Test.CheckResult<double>(v.W, 32, "Изменение W не работает!");
				v = v.Add(Vector4D.One);
				Test.CheckResult<double>(v.X, 33, "Изменение Add X не работает!");
				Test.CheckResult<double>(v.Y, 33, "Изменение Add Y не работает!");
				Test.CheckResult<double>(v.Z, 33, "Изменение Add Z не работает!");
				Test.CheckResult<double>(v.W, 33, "Изменение Add W не работает!");
				v = v.Sub(Vector4D.One);
				Test.CheckResult<double>(v.X, 32, "Изменение Sub X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Sub Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Sub Z не работает!");
				Test.CheckResult<double>(v.W, 32, "Изменение Sub W не работает!");
				v = v.Mul(Vector4D.Double);
				Test.CheckResult<double>(v.X, 64, "Изменение Mul X не работает!");
				Test.CheckResult<double>(v.Y, 64, "Изменение Mul Y не работает!");
				Test.CheckResult<double>(v.Z, 64, "Изменение Mul Z не работает!");
				Test.CheckResult<double>(v.W, 64, "Изменение Mul W не работает!");
				v = v.Div(Vector4D.Double);
				Test.CheckResult<double>(v.X, 32, "Изменение Div X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Div Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Div Z не работает!");
				Test.CheckResult<double>(v.W, 32, "Изменение Div W не работает!");
				v = v + Vector4D.One;
				Test.CheckResult<double>(v.X, 33, "Изменение Add 2 X не работает!");
				Test.CheckResult<double>(v.Y, 33, "Изменение Add 2 Y не работает!");
				Test.CheckResult<double>(v.Z, 33, "Изменение Add 2 Z не работает!");
				Test.CheckResult<double>(v.W, 33, "Изменение Add 2 W не работает!");
				v = v - Vector4D.One;
				Test.CheckResult<double>(v.X, 32, "Изменение Sub 2 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Sub 2 Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Sub 2 Z не работает!");
				Test.CheckResult<double>(v.W, 32, "Изменение Sub 2 W не работает!");
				v = v * Vector4D.Double;
				Test.CheckResult<double>(v.X, 64, "Изменение Mul 2 X не работает!");
				Test.CheckResult<double>(v.Y, 64, "Изменение Mul 2 Y не работает!");
				Test.CheckResult<double>(v.Z, 64, "Изменение Mul 2 Z не работает!");
				Test.CheckResult<double>(v.W, 64, "Изменение Mul 2 W не работает!");
				v = v / Vector4D.Double;
				Test.CheckResult<double>(v.X, 32, "Изменение Div 2 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Div 2 Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Div 2 Z не работает!");
				Test.CheckResult<double>(v.W, 32, "Изменение Div 2 W не работает!");
				v = v + 1;
				Test.CheckResult<double>(v.X, 33, "Изменение Add 3 X не работает!");
				Test.CheckResult<double>(v.Y, 33, "Изменение Add 3 Y не работает!");
				Test.CheckResult<double>(v.Z, 33, "Изменение Add 3 Z не работает!");
				Test.CheckResult<double>(v.W, 33, "Изменение Add 3 W не работает!");
				v = v - 1;
				Test.CheckResult<double>(v.X, 32, "Изменение Sub 3 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Sub 3 Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Sub 3 Z не работает!");
				Test.CheckResult<double>(v.W, 32, "Изменение Sub 3 W не работает!");
				v = v * 2;
				Test.CheckResult<double>(v.X, 64, "Изменение Mul 3 X не работает!");
				Test.CheckResult<double>(v.Y, 64, "Изменение Mul 3 Y не работает!");
				Test.CheckResult<double>(v.Z, 64, "Изменение Mul 3 Z не работает!");
				Test.CheckResult<double>(v.W, 64, "Изменение Mul 3 W не работает!");
				v = v / 2;
				Test.CheckResult<double>(v.X, 32, "Изменение Div 3 X не работает!");
				Test.CheckResult<double>(v.Y, 32, "Изменение Div 3 Y не работает!");
				Test.CheckResult<double>(v.Z, 32, "Изменение Div 3 Z не работает!");
				Test.CheckResult<double>(v.W, 32, "Изменение Div 3 W не работает!");
			});
			Test.F("Сравнение", () => {
				var v = Vector4D.Right.Mul(Vector4D.Double);
				Test.CheckResult(v == null, false, "Сравнение не работает!");
				Test.CheckResult(v != null, true, "Сравнение 2 не работает!");
				Test.CheckResult(v == v, true, "Сравнение 3 не работает!");
				Test.CheckResult(v != v, false, "Сравнение 4 не работает!");
				Test.CheckResult(v == Vector4D.Right.Mul(Vector4D.Double), true, "Сравнение 5 не работает!");
				Test.CheckResult(v == Vector4D.One, false, "Сравнение 6 не работает!");
			});
		});
	}
}